<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Customer Referrals
    |--------------------------------------------------------------------------
    |
    | A customer shares their own referral code (generated by the client).
    | When a new customer signs up with it, the referrer earns bonuses into a
    | separate referral wallet as the new customer reaches each milestone.
    |
    | enabled         off stops new referrals and new bonuses. Existing
    |                 referrals and balances are kept.
    | effective_from  first day (app timezone, Y-m-d) a signup can create a
    |                 referral. Customers who signed up before it never count.
    | bonuses         KES paid to the referrer per milestone:
    |                 signup         the referred customer is verified (email
    |                                and phone, reported by the client)
    |                 first_deposit  the referred customer's first wallet
    |                                deposit, paid once they are verified
    |
    */

    'enabled' => (bool) env('REFERRALS_ENABLED', true),

    'effective_from' => env('REFERRALS_EFFECTIVE_FROM'),

    'bonuses' => [
        'signup' => (float) env('REFERRALS_SIGNUP_BONUS', 10),
        'first_deposit' => (float) env('REFERRALS_FIRST_DEPOSIT_BONUS', 10),
    ],

    'withdrawals' => [
        'enabled' => (bool) env('REFERRALS_WITHDRAWALS_ENABLED', true),
        'minimum' => (int) env('REFERRALS_WITHDRAWAL_MINIMUM', 50),
    ],

];
