<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Facades\DB;

class GameTransaction extends Model
{
    /** @use HasFactory<\Database\Factories\WalletFactory> */
    use HasFactory;

    protected $table = 'game_transactions';

    protected $fillable = [
        'game_wallet_id',
        'customer_id',
        'payment_type',
        'amount',
        'status'
    ];

    protected static function boot(){
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($gameTransaction){
            DB::transaction(function () use ($gameTransaction) {
                $customer = Customer::with('wallet')->find($gameTransaction->customer_id);
                $gameWallet = GameWallet::find($gameTransaction->game_wallet_id);

                if ($gameTransaction->payment_type === 'deposit' && $customer && $customer->wallet && $gameWallet) {
                    // Update game wallet balance
                    $gameWallet->balance += $gameTransaction->amount;
                    $gameWallet->save();

                    // Deduct customer wallet balance
                    $customer->wallet->balance -= $gameTransaction->amount;
                    $customer->wallet->save();
                }
            });
        });
    }

    public function gameWallet(){
        return $this->belongsTo(GameWallet::class, 'game_wallet_id');
    }

    public function customer(){
        return $this->belongsTo(Customer::class);
    }
}
